modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/NoComment1105/DeepslateCutting/issues"
license = "LGPL-3.0"
showAsResourcePack = false

[[mods]]
modId = "deepslatecutting_forge"
version = "${version}"
displayName = "DeepslateCutting"
displayURL = "https://github.com/NoComment1105/DeepslateCutting"
authors = "NoComment1105"
description = '''
This mod allows you to use regular Deepslate in a stonecutter!
'''
logoFile = "icon.png"

[[dependencies.deepslatecutting_forge]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.deepslatecutting_forge]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"